from flask import Flask, render_template, request
from google import genai
import json
import re
import sqlite3

from config import GEMINI_API_KEY, DEPARTMENT_EMAILS
from tools import send_email, mark_urgent, store_db, init_db

app = Flask(__name__)

# Initialize database on startup
init_db()

# Configure Gemini is now done per client instance in google.genai
    
def analyze_complaint(complaint_text):
    """
    Uses Gemini API to analyze the complaint and extract structured information.
    """
    if GEMINI_API_KEY == "your_gemini_key":
        # Fallback for when API key is not set (for local testing without key)
        is_urg = mark_urgent(complaint_text)
        return {
            "summary": "Simulated summary of the problem: " + complaint_text[:50] + "...",
            "department": "Admin",
            "urgency": "High" if is_urg else "Medium",
            "action_steps": "Investigate the issue and contact the student."
        }

    try:
        client = genai.Client(api_key=GEMINI_API_KEY)
        
        prompt = f"""
        Analyze the following student complaint and extract the details in a structured JSON format.
        Complaint: "{complaint_text}"
        
        You must output ONLY a valid JSON object with the following structure:
        {{
            "summary": "A concise 1-sentence summary of the problem",
            "department": "One of: Technical, Accounts, Admin, Academics",
            "urgency": "One of: Emergency, High, Medium, Low",
            "action_steps": "A short 1-sentence suggested action step"
        }}
        
        Rules for classification:
        - Technical: WiFi, systems, equipment, portal login issues.
        - Accounts: Fees, refunds, scholarships, payments.
        - Academics: Grades, exams, courses, faculty issues.
        - Admin: Hostel, policies, campus facilities, general inquiries.
        
        Rules for urgency (IMPORTANT: Analyze the TONE and ACTUAL IMPACT of the situation. Do not just look for keywords like 'urgent'. If the situation causes stress or severe consequences, mark it accordingly):
        - Emergency: Safety, health, immediate critical damage.
        - High: Affects learning/work immediately, or risks academic progress (e.g., "unable to pay fees, so my exam might get cancelled", wifi down before exam, portal deadline).
        - Medium: Convenience-related or can wait a few days.
        - Low: General inquiry.
        """
        
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        text = response.text.strip()
        
        # Clean up potential markdown formatting around the JSON
        if text.startswith("```json"):
            text = text[7:]
        if text.endswith("```"):
            text = text[:-3]
            
        result = json.loads(text)
        
        # Ensure fallback for department
        if result.get("department") not in DEPARTMENT_EMAILS:
            result["department"] = "Admin"
            
        return result
    except Exception as e:
        print(f"Gemini API Error: {e}")
        # Fallback
        is_urg = mark_urgent(complaint_text)
        return {
            "summary": f"Failed to analyze. Original: {complaint_text[:50]}",
            "department": "Admin",
            "urgency": "High" if is_urg else "Low",
            "action_steps": "Manual review required."
        }

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/submit", methods=["POST"])
def submit():
    student_name = request.form.get("name")
    enrollment_no = request.form.get("enrollment_no")
    year = request.form.get("year")
    complaint_text = request.form.get("complaint")
    
    # 1. THINK & ANALYZE (Gemini API)
    analysis = analyze_complaint(complaint_text)
    
    # Check manual urgency heuristic to bump urgency if Gemini missed it
    if mark_urgent(complaint_text) and analysis["urgency"] in ["Medium", "Low"]:
        analysis["urgency"] = "High"
        
    department = analysis["department"]
    dept_email = DEPARTMENT_EMAILS.get(department, DEPARTMENT_EMAILS["Admin"])
    
    # 2. PLAN & ACT: Create Email
    email_subject = f"[{analysis['urgency'].upper()}] Complaint from {student_name} ({enrollment_no})"
    email_body = f"""
New Student Complaint Received

Student Details:
- Name: {student_name}
- Enrollment No: {enrollment_no}
- Year: {year}

Complaint Analysis:
- Department Routed: {department}
- Urgency Level: {analysis['urgency']}

Summary of Issue:
{analysis['summary']}

Original Complaint:
"{complaint_text}"

Suggested Action:
{analysis['action_steps']}

---
This email was generated by the ComplaintFlow Autonomous AI Agent.
"""
    
    # 3. Send Email
    email_status = send_email(dept_email, email_subject, email_body)
    print(email_status)
    
    # 4. Persist to Database
    db_data = {
        "name": student_name,
        "enrollment_no": enrollment_no,
        "year": year,
        "complaint": complaint_text,
        "summary": analysis["summary"],
        "department": department,
        "urgency": analysis["urgency"]
    }
    db_status = store_db(db_data)
    print(db_status)
    
    # Expected Resolution based on urgency
    resolution_map = {
        "Emergency": "Under 4 Hours",
        "High": "Within 24 Hours",
        "Medium": "2-3 Days",
        "Low": "Up to 7 Days"
    }
    timeline = resolution_map.get(analysis["urgency"], "Within 24 Hours")
    
    # Render Result
    return render_template("result.html", 
                           summary=analysis["summary"],
                           department_email=dept_email,
                           urgency=analysis["urgency"],
                           timeline=timeline)

@app.route("/check-followup", methods=["GET"])
def check_followup():
    """
    Endpoint intended to be called by a cron job every hour.
    Checks the database for complaints older than 24 hours that are still 'Pending'.
    """
    try:
        conn = sqlite3.connect("database.db")
        cursor = conn.cursor()
        
        # In SQLite, we can use datetime functions to find rows older than 24 hours
        # For simplicity in this demo, let's just query Pending complaints
        cursor.execute('''
            SELECT id, student_name, department, summary 
            FROM complaints 
            WHERE status = 'Pending' AND timestamp <= datetime('now', '-1 day')
        ''')
        pending_issues = cursor.fetchall()
        
        count = 0
        for issue in pending_issues:
            issue_id, name, dept, summary = issue
            dept_email = DEPARTMENT_EMAILS.get(dept, DEPARTMENT_EMAILS["Admin"])
            
            # Send reminder email
            subject = f"[REMINDER] Unresolved Complaint #{issue_id} from {name}"
            body = f"This is an automated 24-hour reminder.\n\nIssue Summary:\n{summary}\n\nPlease update the status of this complaint."
            send_email(dept_email, subject, body)
            count += 1
            
        conn.close()
        return {"status": "success", "reminders_sent": count}
    except Exception as e:
        return {"status": "error", "message": str(e)}, 500

if __name__ == "__main__":
    app.run(debug=True, port=5000)
